import 'package:flutter/material.dart';
import 'dart:math' as math;
import 'package:shared_preferences/shared_preferences.dart';
//import '../AppBar.dart';
import '../AnimeWallpaperApp.dart';
// --- Placeholder for your main app screen ---
// In your actual project, you would import this from 'lib/AppBar.dart'.
// I've included it here to make the example runnable.

// --- End of Placeholder ---

// Main application widget
class AIWallpaperApp extends StatelessWidget {
  const AIWallpaperApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AI Wallpaper App',
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: Colors.black,
        fontFamily: 'Inter',
      ),
      home: const OnboardingScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

// The main onboarding screen widget that holds the PageView
class OnboardingScreen extends StatefulWidget {
  const OnboardingScreen({super.key});

  @override
  State<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen>
    with TickerProviderStateMixin {
  late PageController _pageController;
  late AnimationController _animationController;
  int _currentPage = 0;

  // List of onboarding page data
  final List<OnboardingPageData> _onboardingPages = [
    OnboardingPageData(
      title: "AI-Crafted Wallpapers",
      description:
          "Discover a universe of wallpapers generated by cutting-edge AI.",
      child: const GlowingWallpaperPreview(),
    ),
    OnboardingPageData(
      title: "Unique & Personalized",
      description: "Every design is one-of-a-kind, tailored to your style.",
      child: const PersonalizedDesignsMockup(),
    ),
    OnboardingPageData(
      title: "Endless Creativity",
      description: "Explore an infinite gallery that's always growing.",
      child: const AnimatedWallpaperGrid(),
    ),
  ];

  @override
  void initState() {
    super.initState();
    _checkIfFirstTime(); // Check if onboarding should be shown

    _pageController = PageController();
    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 500),
    );

    _pageController.addListener(() {
      int nextPage = _pageController.page!.round();
      if (_currentPage != nextPage) {
        setState(() {
          _currentPage = nextPage;
        });
        if (_currentPage == _onboardingPages.length - 1) {
          _animationController.forward();
        } else {
          _animationController.reverse();
        }
      }
    });
  }

  // New method to check shared_preferences and navigate if needed
  Future<void> _checkIfFirstTime() async {
    // IMPORTANT: Add shared_preferences to your pubspec.yaml
    // dependencies:
    //   shared_preferences: ^2.0.15
    SharedPreferences prefs = await SharedPreferences.getInstance();
    // Use `true` for testing, `false` for production
    bool seenOnboarding = prefs.getBool('seenOnboarding') ?? false;

    if (seenOnboarding) {
      _navigateToHome();
    }
  }

  void _navigateToHome() {
    // Navigate to your main app screen and remove onboarding from the stack
    Navigator.of(context).pushReplacement(
      MaterialPageRoute(builder: (_) => const AnimeWallpaperApp()),
    );
  }

  // New method to mark onboarding as seen
  Future<void> _completeOnboarding() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setBool('seenOnboarding', true);
    _navigateToHome();
  }

  @override
  void dispose() {
    _pageController.dispose();
    _animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Stack(
          children: [
            PageView.builder(
              controller: _pageController,
              itemCount: _onboardingPages.length,
              itemBuilder: (context, index) {
                return OnboardingPage(
                  data: _onboardingPages[index],
                  currentPage: _currentPage,
                  index: index,
                );
              },
            ),
            Align(
              alignment: Alignment.bottomCenter,
              child: Padding(
                padding: const EdgeInsets.only(bottom: 40.0),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    PageIndicator(
                      currentPage: _currentPage,
                      pageCount: _onboardingPages.length,
                    ),
                    const SizedBox(height: 40),
                    FadeTransition(
                      opacity: _animationController,
                      child: GetStartedButton(
                        // Pass the completion function to the button
                        onPressed: _completeOnboarding,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// Data model for a single onboarding page
class OnboardingPageData {
  final String title;
  final String description;
  final Widget child;

  OnboardingPageData({
    required this.title,
    required this.description,
    required this.child,
  });
}

// Widget for a single onboarding page content
class OnboardingPage extends StatelessWidget {
  final OnboardingPageData data;
  final int currentPage;
  final int index;

  const OnboardingPage({
    super.key,
    required this.data,
    required this.currentPage,
    required this.index,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 24.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          data.child,
          const SizedBox(height: 60),
          AnimatedOpacity(
            duration: const Duration(milliseconds: 600),
            opacity: currentPage == index ? 1.0 : 0.0,
            child: Text(
              data.title,
              textAlign: TextAlign.center,
              style: const TextStyle(
                fontSize: 26,
                fontWeight: FontWeight.bold,
                color: Colors.white,
                letterSpacing: 0.5,
              ),
            ),
          ),
          const SizedBox(height: 16),
          AnimatedOpacity(
            duration: const Duration(milliseconds: 600),
            opacity: currentPage == index ? 1.0 : 0.0,
            child: Text(
              data.description,
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 16,
                color: Colors.grey[400],
                height: 1.5,
              ),
            ),
          ),
          const SizedBox(height: 120),
        ],
      ),
    );
  }
}

// --- Custom Widgets for Onboarding Pages ---

// 1. Glowing Wallpaper Preview for the first screen
class GlowingWallpaperPreview extends StatelessWidget {
  const GlowingWallpaperPreview({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 220,
      height: 380,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(24),
        boxShadow: [
          BoxShadow(
            color: Colors.cyan.withOpacity(0.5),
            blurRadius: 25,
            spreadRadius: 5,
          ),
          BoxShadow(
            color: Colors.purple.withOpacity(0.3),
            blurRadius: 40,
            spreadRadius: 10,
          ),
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(24),
        child: Image.network(
          'https://www.alhyane.fun/ethanwalkerapps/splash/10.jpg',
          fit: BoxFit.cover,
          errorBuilder: (context, error, stackTrace) => Container(
            color: Colors.grey[900],
            child: const Center(child: Text('Image not found')),
          ),
        ),
      ),
    );
  }
}

// 2. Personalized Designs Mockup for the second screen
class PersonalizedDesignsMockup extends StatelessWidget {
  const PersonalizedDesignsMockup({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 300,
      height: 380,
      child: Stack(
        alignment: Alignment.center,
        children: [
          _buildMockupCard(
            'https://www.alhyane.fun/ethanwalkerapps/splash/12.jpg',
            -45,
            -20,
            -15.0,
          ),
          _buildMockupCard(
            'https://www.alhyane.fun/ethanwalkerapps/splash/13.jpg',
            45,
            20,
            15.0,
          ),
          _buildMockupCard(
            'https://www.alhyane.fun/ethanwalkerapps/splash/14.jpg',
            0,
            0,
            0,
          ),
        ],
      ),
    );
  }

  Widget _buildMockupCard(
      String imageUrl, double xOffset, double yOffset, double angle) {
    return Transform.translate(
      offset: Offset(xOffset, yOffset),
      child: Transform.rotate(
        angle: angle * (math.pi / 180),
        child: Container(
          width: 150,
          height: 260,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.4),
                blurRadius: 15,
                offset: const Offset(5, 5),
              )
            ],
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(16),
            child: Image.network(
              imageUrl,
              fit: BoxFit.cover,
              errorBuilder: (context, error, stackTrace) => Container(
                color: Colors.grey[900],
                child: const Center(child: Text('...')),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

// 3. Animated Wallpaper Grid for the third screen
class AnimatedWallpaperGrid extends StatefulWidget {
  const AnimatedWallpaperGrid({super.key});

  @override
  State<AnimatedWallpaperGrid> createState() => _AnimatedWallpaperGridState();
}

class _AnimatedWallpaperGridState extends State<AnimatedWallpaperGrid> {
  bool _isAnimated = false;

  @override
  void initState() {
    super.initState();
    // Trigger animation shortly after the widget is built
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        setState(() {
          _isAnimated = true;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 300,
      height: 380,
      child: GridView.builder(
        gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 3,
          crossAxisSpacing: 12,
          mainAxisSpacing: 12,
        ),
        itemCount: 9,
        physics: const NeverScrollableScrollPhysics(),
        itemBuilder: (context, index) {
          // The URL is now created dynamically from your host.
          // index is 0-8, so we add 1 to get image names 1-9.
          final imageUrl =
              'https://www.alhyane.fun/ethanwalkerapps/splash/${index + 1}.jpg';

          return AnimatedContainer(
            duration: Duration(milliseconds: 500 + (index * 100)),
            curve: Curves.easeInOut,
            transform: Matrix4.translationValues(0, _isAnimated ? 0 : 30, 0),
            child: Opacity(
              opacity: _isAnimated ? 1.0 : 0.0,
              child: ClipRRect(
                borderRadius: BorderRadius.circular(12),
                child: Image.network(
                  imageUrl, // Use the new dynamic URL here
                  fit: BoxFit.cover,
                  // Added a loading builder for a better user experience
                  loadingBuilder: (BuildContext context, Widget child,
                      ImageChunkEvent? loadingProgress) {
                    if (loadingProgress == null) return child;
                    return Center(
                      child: CircularProgressIndicator(
                        value: loadingProgress.expectedTotalBytes != null
                            ? loadingProgress.cumulativeBytesLoaded /
                                loadingProgress.expectedTotalBytes!
                            : null,
                        strokeWidth: 2.0,
                        color: Colors.white,
                      ),
                    );
                  },
                  errorBuilder: (context, error, stackTrace) => Container(
                    color: Colors.grey[900],
                    child: const Icon(Icons.error_outline,
                        color: Colors.redAccent),
                  ),
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}
// --- Common UI Components ---

// Custom page indicator widget
class PageIndicator extends StatelessWidget {
  final int currentPage;
  final int pageCount;

  const PageIndicator({
    super.key,
    required this.currentPage,
    required this.pageCount,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: List.generate(pageCount, (index) {
        return AnimatedContainer(
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeInOut,
          margin: const EdgeInsets.symmetric(horizontal: 5),
          width: currentPage == index ? 24 : 8,
          height: 8,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(4),
            gradient: currentPage == index
                ? const LinearGradient(
                    colors: [Colors.cyan, Colors.purple],
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                  )
                : null,
            color: currentPage != index ? Colors.grey[800] : null,
          ),
        );
      }),
    );
  }
}

// "Get Started" button with a glowing gradient
class GetStartedButton extends StatelessWidget {
  final VoidCallback onPressed; // Changed to accept a function

  const GetStartedButton({
    super.key,
    required this.onPressed,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onPressed, // Use the passed function here
      child: Container(
        width: 250,
        height: 55,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30),
          gradient: const LinearGradient(
            colors: [Colors.cyan, Colors.purple],
            begin: Alignment.centerLeft,
            end: Alignment.centerRight,
          ),
          boxShadow: [
            BoxShadow(
              color: Colors.purple.withOpacity(0.5),
              blurRadius: 20,
              offset: const Offset(0, 5),
            ),
            BoxShadow(
              color: Colors.cyan.withOpacity(0.5),
              blurRadius: 20,
              offset: const Offset(0, 5),
            ),
          ],
        ),
        child: const Center(
          child: Text(
            'Get Started',
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: Colors.white,
              letterSpacing: 1,
            ),
          ),
        ),
      ),
    );
  }
}
